accounts/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_view
from .  import views as v2

app_name = 'accounts'


urlpatterns = [
    path('login', auth_view.LoginView.as_view(
        template_name='accounts/login.html'
    ), name='login'),
    path('logout', auth_view.LogoutView.as_view(
        template_name='accounts/login.html'
    ), name='logout'),

    path('tempo', v2.tempo, name='tempo'),
    path('incluirUser', v2.incluirUser, name='incluirUser'),


]

app01/urls.py
from  django.urls import include, path
from django.contrib import admin
from . import views as v1

app_name = 'app01'

urlpatterns = [

    path('listFolhaResumo', v1.listFolhaResumo, name='listFolhaResumo'),
    #path('imprimirCSVFolha', v1.imprimirCSVFolha, name='imprimirCSVFolha'),
    path('importacaoFolhaExcel', v1.importacaoFolhaExcel, name='importacaoFolhaExcel'),
    path('planilhaErrada', v1.planilhaErrada, name='planilhaErrada'),
    path('listSomaEventos', v1.listSomaEventos, name='listSomaEventos'),
    path('consultarTabelas', v1.consultarTabelas, name='consultarTabelas'),
    path('folhasProcessadas', v1.folhasProcessadas, name='folhasProcessadas'),
    path('imprimirFolhaLayout', v1.imprimirFolhaLayout, name='imprimirFolhaLayout'),
]

core/urls.py
from  django.urls import include, path
from django.contrib import admin
from . import views as v1

app_name = 'core'

urlpatterns = [
    path('', v1.home, name='home'),
    
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def home(request):
	usuario = ''
	user_name = request.user.username
	return render (request, 'core/home.html', { 'usuario': user_name})


def sessao(request):
    if not request.session.get('username'):
        request.session['username'] = request.user.username
    return

core/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" >
    <meta name="description" content="Simple MOOC : Uma simples plataforma de ensino a distancia" />
    <title>Utilitários</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.3.0/pure-min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/menu.css' %}" />
<style>
    .tab_layout {font-size: 12px;text-align: center;}
    .wrapper {
        display: grid;
        grid-template-columns: 350px 400px 340px;
    }
</style>

</head>
<body>
<div class="header">


<ul class="menuH decor1">


<li><a href="#" class="arrow">1 Processamentos</a>
<ul>
<li><a href="{% url 'app01:importacaoFolhaExcel' %}">1.1 Folha</a></li>


            </ul>
        </li>

        <li><a href="#" class="arrow">2 Consultas</a>

            <ul>
            <li><a href="{% url 'app01:listSomaEventos' %}">2.1 Lista Soma por Eventos</a></li>            
            <li><a href="{% url 'app01:listFolhaResumo' %}">2.2 Lista Soma por Setores</a></li>
            <li><a href="{% url 'app01:folhasProcessadas' %}">2.3 Folhas Processadas</a></li>
            
<li><a href="{% url 'app01:imprimirFolhaLayout' %}">2.4 Modelo Base Excel</a></li>            
            </ul>
        </li>

        <li><a href="#" class="arrow">3 Cadastro</a>
            <ul>
            <li><a href="{% url 'app01:consultarTabelas' %}">3.1 Funcoes e Eventos</a></li>
        </ul>

        </li>




        
        {% if user.is_authenticated %}
         <li><a href="{% url 'accounts:logout'  %}">3. Sair</a>
         {% else %}
         <li><a href="{% url 'accounts:login'  %}">3. Login</a>
         {% endif %}
        <!--
        <li><a href="#3" class="arrow">3. Login</a>
            <ul class="dropToLeft">
                <li><a>3.1 Down Menu Deoms</a></li>
                <li><a>3.2 Web Down Menu Instruction</a></li>
                <li><a>3.3 Cross Browser Compatibility</a></li>
                <li><a>3.4 Down Menu Directions</a></li>
            </ul>
        </li>
        -->
    </ul>

  
  </div>
<div class="content">
    {%  block content %} {% endblock %}
    <div class="footer">
        Utilitários WEB.
     </div>
  </div>
  <script src="http://yui.yahooapis.com/3.12.0/build/yui/yui-min.js"></script>
</body>
</html>
 

core/templates/base2.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>  

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://igorescobar.github.io/jQuery-Mask-Plugin/js/jquery.mask.min.js"></script>        


<!-- Isolated Version of Bootstrap, not needed if your site already uses Bootstrap -->
<link rel="stylesheet" href="https://formden.com/static/cdn/bootstrap-iso.css" />

<!-- Bootstrap Date-Picker Plugin -->

    <title>*Sistema Saj</title>
  </head>
  <body>
  <a href="{% url 'core:home'  %}"><img src="{% static 'imagens/seta_voltar.jpg' %}" alt="Voltar" height="72" width="72"></a>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-8">
          <hr class="mt-0 mb-4">
          {% block sidebar %}<!-- insert default navigation text for every page -->{% endblock %}
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>


  <!-- JS files: jQuery first, then Popper.js, then Bootstrap JS -->
  <!--
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

-->
    
  </body>
</html>