app01/urls.py
from  django.urls import include, path
from django.contrib import admin
from . import views as v1

app_name = 'app01'

urlpatterns = [

    path('listFolhaResumo', v1.listFolhaResumo, name='listFolhaResumo'),
    #path('imprimirCSVFolha', v1.imprimirCSVFolha, name='imprimirCSVFolha'),
    path('importacaoFolhaExcel', v1.importacaoFolhaExcel, name='importacaoFolhaExcel'),
    path('planilhaErrada', v1.planilhaErrada, name='planilhaErrada'),
    path('listSomaEventos', v1.listSomaEventos, name='listSomaEventos'),
    path('consultarTabelas', v1.consultarTabelas, name='consultarTabelas'),
    path('folhasProcessadas', v1.folhasProcessadas, name='folhasProcessadas'),
    path('imprimirFolhaLayout', v1.imprimirFolhaLayout, name='imprimirFolhaLayout'),
]

core/urls.py
from  django.urls import include, path
from django.contrib import admin
from . import views as v1

app_name = 'core'

urlpatterns = [
    path('', v1.home, name='home'),
    
]

app01/models.py
from __future__ import unicode_literals
from django.db import connection
from django.db import models
from . import choices


#SET FOREIGN_KEY_CHECKS = 0;
#heroku run python manage.py shell --app civitas-plataforma

# TUTORIAL How to Reset Migrations
#https://simpleisbetterthancomplex.com/tutorial/2016/07/26/how-to-reset-migrations.html

    #Restaurar o auto-increment no pgadmin
#http://blog.abraseucodigo.com.br/problemas-com-postgres-django-sequences.html
'''
neste exemplo estamos corrigindo o problema na tabela eventos_cv
SELECT c.relname FROM pg_class c WHERE c.relkind = 'S';
select * from eventos_cv_id_evento_cv_seq
select count(*) from eventos_cv
SELECT setval('eventos_cv_id_evento_cv_seq', 137);

observacao: o valor 137 é o resultado do select  count(*).
from app01.models import Folhames,Folhaevento,Refeventos,Evento
Folhames.objects.filter(id_municipio=85).delete()

'''



#sudo /opt/pentaho/client-tools/data-integration/spoon.sh


# lista = [f.name for f in User._meta.get_fields()]

#https://www.sankalpjonna.com/learn-django/running-a-bulk-update-with-django



#-----------------------deletando varios objetos -------------------------------------------------------
'''
from django.db import connection 
from app.account.models import Store 
from app.recommendations.models import Recommendation

store = Store.objects.get(name=‘amazon’) 
recommendations = Recommendation.objects.filter(store=store) 
if recommendations.exists(): 
    cursor = connection.cursor()
    cursor.execute(“DELETE FROM app_recommendation WHERE store_id = %s”, [store.id])

'''
#2022-04-19
#git push heroku master

#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
#---------------------------------------------------------------------------

class Municipio(models.Model):  
    id_municipio = models.AutoField(primary_key=True)
    municipio = models.CharField(max_length=100)
    empresa = models.CharField(max_length=100,default='')
    entidade = models.CharField(max_length=100,default='')

    def __str__(self):
        return self.municipio

    class Meta:
            db_table = "municipios"        

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        

class Vinculo(models.Model):  
    id_vinculo = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    vinculo = models.CharField(max_length=100)

    def __str__(self):
        return self.vinculo

    class Meta:
        db_table = 'vinculos'
        constraints = [
            models.UniqueConstraint(fields=['id_municipio', 'vinculo'], name='unique_vinculo')
        ]


    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        

class LogErro(models.Model):  
    id_logerro = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    anomes = models.IntegerField(default=0)
    numero_linha = models.IntegerField(null=True)
    codigo = models.CharField(max_length=100, null=True)
    observacao = models.CharField(max_length=255, null=True)
    created_at = models.DateTimeField(auto_now_add=True)    

    def __str__(self):
        return self.codigo

    class Meta:
        db_table = 'logerro'


    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        



class Funcao(models.Model):  
    id_funcao = models.AutoField(primary_key=True)
    id_municipio =  models.IntegerField()
    empresa = models.CharField(max_length=50,default='')
    funcao = models.CharField(max_length=100)
    id_funcao_cv = models.IntegerField(default=0)
    cancelado = models.CharField(max_length=1,default='N')

    def __str__(self):
        return self.funcao

    class Meta:
        db_table = 'funcoes'

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        



class Servidor(models.Model):  
    id_servidor = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    nome = models.CharField(max_length=100)
    cod_servidor = models.IntegerField()
    cpf = models.CharField(max_length=20,default='')
    data_admissao = models.DateField(null=True)
    ativo = models.IntegerField(default=1)

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'servidores'
        constraints = [
            models.UniqueConstraint(fields=['id_municipio', 'cod_servidor'], name='servidor_unique')
        ]
        indexes = [
            models.Index(fields=['id_municipio'])
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        



class Secretaria(models.Model):  
    id_secretaria = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    secretaria = models.CharField(max_length=100)

    def __str__(self):
        return self.secretaria

    class Meta:
        db_table = "secretarias"  
        constraints = [
            models.UniqueConstraint(fields=['id_municipio','secretaria'], name='unique_secretaria')
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        



class Evento(models.Model):  
    PROVDESC_CHOICES = [
        ('',''),
        ('V','VANTAGEM'),
        ('D','DESCONTO'),
    ]

    id_evento = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    empresa = models.CharField(max_length=50,default='')
    tipo = models.CharField(max_length=9,choices=PROVDESC_CHOICES,default='V')
    evento = models.CharField(max_length=50)
    cancelado = models.CharField(max_length=1,default='N')
    exibe_excel = models.IntegerField(default=1)
    ordenacao = models.IntegerField(default=0)
    cl_orcamentaria = models.CharField(max_length=6, null=True)
    id_evento_cv = models.IntegerField(default=0)

    def __str__(self):
        return self.evento

    class Meta:
        db_table = 'eventos'

        

class Setor(models.Model):  
    id_setor = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField()
    secretaria = models.ForeignKey(Secretaria,on_delete=models.CASCADE)
    setor = models.CharField(max_length=100)

    def __str__(self):
        return self.setor


    class Meta:
        db_table = 'setores'
        constraints = [
            models.UniqueConstraint(fields=['id_municipio','secretaria', 'setor' ], name='unique_setor')
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        




class Folhames(models.Model):
    id_folha = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField(null=True)
    anomes = models.IntegerField()
    cod_servidor = models.IntegerField()
    cpf = models.CharField(max_length=11, null=True)
    id_secretaria = models.IntegerField(null=True)
    id_setor = models.IntegerField(null=True)
    id_funcao = models.IntegerField(null=True)
    id_vinculo = models.IntegerField(null=True)
    previdencia = models.CharField(max_length=6, null=True)
    carga_horaria = models.IntegerField(null=True)
    dias = models.CharField(max_length=30, null=True)
    data_criacao = models.DateTimeField(null=True)

    def __str__(self):
        return self.cod_servidor

    class Meta:
        db_table = 'folhames'
        indexes = [
            models.Index(fields=['id_municipio','anomes'])
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        




class Folhaevento(models.Model):
    id_folhaevento = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField(null=True)
    anomes = models.IntegerField()
    cod_servidor = models.IntegerField()
    previdencia = models.CharField(max_length=6, null=True)
    cl_orcamentaria = models.CharField(max_length=6, null=True)
    id_evento = models.IntegerField(null=True)
    tipo = models.CharField(max_length=1, null=True)
    valor = models.DecimalField(max_digits=9, decimal_places=2, default=0)

    def __str__(self):
        return self.cod_servidor

    class Meta:
        db_table = 'folhaeventos'
        indexes = [
            models.Index(fields=['id_municipio','anomes'])
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        


class Refeventos(models.Model):  
    id_ref = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField(null=True)
    anomes = models.IntegerField()
    cod_servidor = models.IntegerField()
    ref_eventos = models.CharField(max_length=100,null=True)

    def __str__(self):
        return self.ref_eventos


    class Meta:
        db_table = 'refeventos'
        constraints = [
            models.UniqueConstraint(fields=['id_municipio','anomes', 'cod_servidor' ], name='unique_refeventos')
        ]

    @classmethod
    def truncate(cls):
        with connection.cursor() as cursor:
            cursor.execute('TRUNCATE TABLE {}'.format(cls._meta.db_table))        



class Funcionario(models.Model):
    id_funcionario = models.AutoField(primary_key=True)
    id_municipio = models.IntegerField(null=True)
    anomes = models.IntegerField(null=True)
    codigo = models.IntegerField(null=True)
    nome_servidor = models.CharField(max_length=100, null=True)
    carga_horaria = models.IntegerField(null=True)
    secretaria = models.CharField(max_length=100,null=True)

app01/forms.py
# -*- encoding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from django.forms.widgets import Select, Widget
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

import datetime
from . import choices,incluirTramitacao



class f001_Tramitacoes(forms.Form):
    OPERACAO_CHOICES=(
        ('BRANCO',''),
        ('EXCLUIR','Excluir tramitacao'),
        ('REAGENDAR','Reagendar tramitacao'),
        ('STATUS','Alterar Status'),
        ('INCLUIR','Incluir tramitacoes'),
    )

    operacao = forms.CharField(
        label = 'Operacao',
        widget=forms.Select(choices=OPERACAO_CHOICES),
        max_length=18
        )    
    tramitacao = forms.CharField(
        label = 'Tipo da tramitacao',
        widget=forms.Select(choices=choices.TRAMITACAO),
        max_length=50
        )
    documento = forms.FileField(label='Arquivo Excel')

    def clean_operacao(self):
        operation = self.cleaned_data.get('operacao')
        if(operation=='BRANCO'):
            raise forms.ValidationError("Informe ass operacao")
        return operation

    def execute(self,current_user):
        operacao = self.cleaned_data.get('operacao')
        tramitacao = self.cleaned_data.get('tramitacao')
        planilha = self.cleaned_data.get('documento')
        if(operacao=='INCLUIR'):
            incluirTramitacao.incluir(planilha,operacao,tramitacao,current_user)
        elif (operacao=='REAGENDAR' or operacao=='EXCLUIR'):
            #importarDecisoes3.exc_Tramitacao(planilha,operacao,tramitacao,current_user)
            incluirTramitacao.incluir(planilha,operacao,tramitacao,current_user)
        elif (operacao=='STATUS'):
            #importarDecisoes3.tramitacao_alterarStatus(planilha,operacao,tramitacao,current_user)
            incluirTramitacao.incluir(planilha,operacao,tramitacao,current_user)

'''
class Folha_01Form(ModelForm):
    OPERACAO_CHOICES=(
        ('BRANCO',''),
        ('EXCLUIR','Excluir tramitacao'),
        ('REAGENDAR','Reagendar tramitacao'),
        ('STATUS','Alterar Status'),
        ('INCLUIR','Incluir tramitacoes'),
    )

    operacao = forms.CharField(
        label = 'Operacao',
        widget=forms.Select(choices=OPERACAO_CHOICES),
        max_length=18
        )    

    tramitacao = forms.CharField(
        label = 'Tipo da tramitacao',
        widget=forms.Select(choices=choices.TRAMITACAO),
        max_length=50
        )
    documento = forms.FileField(label='Arquivo Excel')

    def clean_operacao(self):
        operation = self.cleaned_data.get('operacao')
        if(operation=='BRANCO'):
            raise forms.ValidationError("Informe ass operacao")
        return operation
    

    class Meta:
        model = Foha_01
        fields = ('anomes', 'id_setor','id_funcionario','id_provento','valor')


class Leitura_Zip(forms.Form):
    OPERACAO_CHOICES=(
        ('BRANCO',''),
        ('LER','Incluir departamento(s)'),
    )

    operacao = forms.CharField(
        label = 'Operacao',
        widget=forms.Select(choices=OPERACAO_CHOICES),
        max_length=18
        )    

    municipio = forms.CharField(
        label = 'Operacao',
        widget=forms.Select(choices=choices.MUNICIPIOS),
        max_length=18
        )    

    documento = forms.FileField(label='Arquivo Zip')

    def clean_operacao(self):
        operation = self.cleaned_data.get('operacao')
        if(operation=='BRANCO'):
            raise forms.ValidationError("Informe as operacao")
        return operation

class ListagemDepartamento(forms.Form):
    OPERACAO_CHOICES=(
        ('BRANCO',''),
        ('LER','Incluir departamento(s)'),
    )
    municipio = forms.CharField(
        label = 'Tipo da tramitacao',
        widget=forms.Select(choices=choices.MUNICIPIOS),
        max_length=50
        )
'''

app01/templates/app01/agruparEventos.html
{% extends 'base2.html' %}


{% block content %}
<br/>

<div class="container">
<p align="center">{{ titulo }} - {{ usuario_id }} - {{ usuario_username }}</p>

    
   <form enctype="multipart/form-data" action="{% url 'app01:agrupar-eventos' %}" method="post">
    {%csrf_token%}

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li> {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

   
<div class="row">   

<div class="form-group">
      
    
    <div class="col">
    <label for="id_empresa" class="col-form-label">Empresa</label>
    <select name="empresa"  id="id_empresa" class="form-control" required>
      <option value=""></option>
      <option value="SS">SS Informatica</option>
      <option value="Layout">Layout</option>
      <option value="Aspec">Aspec</option>
    </select>   
    </div>
</div>
</div>


<div class="row">
<div class="form-group">  
  <div class="col">
  
    <div class="fileUpload btn btn-outline-secondary ">
    <label for="upload" class="col-form-label">Arquivo</label>
      <input type="file" id="filename" class="upload" name="filename" required />
    </div>
  </div>
  </div>
</div>  

  
  <br><br>


    <p><span style="display:none">
    <input type="submit" id="submit" value="Entrar 2" >
    </span></p>


    <p>
    <button class="btn btn-success" id="bt_submit" onclick="fnSubmit();" >Executar</button>
    </p>
    <div id="msgDiv" style="display:none">Processo iniciado...</div>



<script>
function fnSubmit(){
  var dados_ok=0;
  if (document.getElementById("filename").value!=""){
      if (document.getElementById("id_municipio").value!=""){
        if (document.getElementById("id_ano").value!=""){
          if (document.getElementById("id_mes").value!=""){
             dados_ok=1;
          }
        }
      }
   }
   if (dados_ok==1){
    document.getElementById("bt_submit").disabled=true;
    document.getElementById("msgDiv").style.display = "block";
    document.getElementById("submit").click();
   }

}
</script>
<style>
#msgDiv {
  width: 550px;
  height: 150px;
  background-color: lightblue;
  font-size: 24px;
}

.mensagem {
  color: red;

}

</style>

   </form>


   <hr>
</div>   
{% endblock %}

app01/templates/app01/folha_01.html
{% extends 'base2.html' %}



{% block sidebar %}

{% endblock %}

 {% block content %}
<br/>


<div class="container">    
<p align="center">{{ titulo_pagina }}</p>
<p align="center">{{ usuario }}</p>
<p align="center">tramitacoes</p>

   <form enctype="multipart/form-data" action="" method="post">{%csrf_token%}

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class="row">   

<div class="form-group">
      
    
    <div class="col">
    <label for="id_grupo" class="col-form-label">Operação</label>
    <select name="operacao"  id="id_operacao" class="form-control">
      {% for id, name in form.operacao.field.widget.choices %}
      <option value="{{ id }}"  >{{ name }}</option>
      {% endfor %}
    </select>   
    </div>
    
    <div class="col">
    <label for="id_tramitacao" class="col-form-label">Tramitação</label>
    <select name="tramitacao"  id="id_tramitacao" class="form-control">
      {% for id, name in form.tramitacao.field.widget.choices %}
      <option value="{{ id }}"  >{{ name }}</option>
      {% endfor %}
    </select> 
    </div>    
    
</div>    
</div>  
  
<div class="row">
<div class="form-group">  
  <div class="col">
  
    <div class="fileUpload btn btn-outline-secondary ">
    <label for="upload" class="col-form-label">Arquivo</label>
      <input type="file" class="upload" name="filename" />
    </div>
  </div>
  </div>
</div>  

   

    <p><span style="display:none"><input type="submit" id="submit" value="Entrar 2" ></span></p>
    <p>
    <button class="btn btn-success" id="bt_submit" onclick="fnSubmit();" >Executar</button>
    </p>
    <div id="msgDiv" style="display:none">Aguarde ja estamos processando!!</div>
<script>
function fnSubmit(){
  document.getElementById("bt_submit").disabled=true;
  document.getElementById("msgDiv").style.display = "block";
  document.getElementById("submit").click();

}
</script>
<style>
#msgDiv {
  width: 550px;
  height: 150px;
  background-color: lightblue;
  font-size: 24px;
}

</style>



   </form>
   <hr>
</div>
</div>
</div>
{% endblock %}

app01/templates/app01/folha_02.html
{% extends 'base2.html' %}



{% block sidebar %}

{% endblock %}

 {% block content %}
<br/>


<div class="container">    
<p align="center">{{ titulo_pagina }}</p>
<p align="center">{{ usuario }}</p>
<p align="center">tramitacoes</p>

   <form enctype="multipart/form-data" action="{% url 'app01:folha_02' %}" method="post">{%csrf_token%}

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class="row">   

<div class="form-group">
      
    
    <div class="col">
    <label for="id_grupo" class="col-form-label">Operação</label>
    <select name="operacao"  id="id_operacao" class="form-control">
      {% for id, name in form.operacao.field.widget.choices %}
      <option value="{{ id }}"  >{{ name }}</option>
      {% endfor %}
    </select>   
    </div>
    
    <div class="col">
    <label for="id_tramitacao" class="col-form-label">Tramitação</label>
    <select name="tramitacao"  id="id_tramitacao" class="form-control">
      {% for id, name in form.tramitacao.field.widget.choices %}
      <option value="{{ id }}"  >{{ name }}</option>
      {% endfor %}
    </select> 
    </div>    
    
</div>    
</div>  
  
<div class="row">
<div class="form-group">  
  <div class="col">
  
    <div class="fileUpload btn btn-outline-secondary ">
    <label for="upload" class="col-form-label">Arquivo</label>
      <input type="file" class="upload" name="filename" />
    </div>
  </div>
  </div>
</div>  

   

    <p><span style="display:none"><input type="submit" id="submit" value="Entrar 2" ></span></p>
    <p>
    <button class="btn btn-success" id="bt_submit" onclick="fnSubmit();" >Executar</button>
    </p>
    <div id="msgDiv" style="display:none">Aguarde ja estamos processando!!</div>
<script>
function fnSubmit(){
  document.getElementById("bt_submit").disabled=true;
  document.getElementById("msgDiv").style.display = "block";
  document.getElementById("submit").click();

}
</script>
<style>
#msgDiv {
  width: 550px;
  height: 150px;
  background-color: lightblue;
  font-size: 24px;
}

</style>



   </form>
   <hr>
</div>
</div>
</div>
{% endblock %}

app01/templates/app01/folhasProcessadas.html
{% extends 'base2.html' %}


{% block content %}
<br/>

<div class="container">
<p align="center">{{ titulo }}</p>

    
   <form action="{% url 'app01:folhasProcessadas' %}" method="post">
    {%csrf_token%}

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

   
<div class="row">   

<div class="form-group">

  
    
    <div class="col">
    <label for="id_municipio" class="col-form-label">Municípios</label>
    <select name="municipio"  id="id_municipio" class="form-control" required>
      <option value="0">Todos</option>
      {% for municipio in municipios %}
        <option value="{{ municipio.id_municipio }}">{{ municipio.municipio }}</option>
    {% endfor %}        
    </select>   
    </div>

    <div class="col">
    <label for="id_empresa" class="col-form-label">Empresa</label>
    <select name="empresa"  id="id_empresa" class="form-control" required>
      <option value="Todas">Todas</option>
        <option value="Aspec">Aspec</option>
        <option value="Layout">Layout</option>
        <option value="SS">SS</option>
    </select>   
    </div>



    <input type='hidden' name="operacao" value='atualizar'>

    <br>
    <h2><span class="mensagem">{{ mensagem }}</span></h2>
    
</div>    
</div>  
  
  <br><br>


    <p><span style="display:none">
    <input type="submit" id="submit" value="Entrar 2" >
    </span></p>


    <p>
    <button class="btn btn-success" id="bt_submit" onclick="fnSubmit();" >Executar</button>
    </p>
    <div id="msgDiv" style="display:none">Processo iniciado...</div>



<script>
function fnSubmit(){
  var dados_ok=0;
  if (document.getElementById("filename").value!=""){
      if (document.getElementById("id_municipio").value!=""){
        if (document.getElementById("id_ano").value!=""){
          if (document.getElementById("id_mes").value!=""){
             dados_ok=1;
          }
        }
      }
   }
   if (dados_ok==1){
    document.getElementById("bt_submit").disabled=true;
    document.getElementById("msgDiv").style.display = "block";
    document.getElementById("submit").click();
   }

}
</script>
<style>
#msgDiv {
  width: 550px;
  height: 150px;
  background-color: lightblue;
  font-size: 24px;
}

.mensagem {
  color: red;
}

.alignRigth {
  text-align: right;
}

.alignCenter {
  text-align: center;
}

.alignLeft {
  text-align: left;
}


</style>

   </form>

   <hr>
</div>
</div>
</div>


   {% if lista_folha %}
   <p>
    {{ municipio }}<br>
    {{ sel_empresa }}
   </p>
   
   <table ><tr class="alignCenter"><th>Item</th><th>Município</th><th>Mês Base</th><th>N.Servidores</th><th>Total das Vantagens</th><th>Data do Processamento</th></tr>
   {% for folha in lista_folha %}

  <tr>
    <td class="alignCenter" >{{ folha.item  }}</td>
    <td class="alignLeft" >{{ folha.municipio  }}</td>
    <td class="alignCenter" >{{ folha.mesref  }}</td>
    <td class="alignRigth" >{{ folha.quantidade  }}</td>
    <td class="alignRigth" >{{ folha.valor  }}</td>
    <td class="alignCenter" >{{ folha.data_criacao  }}</td>


  </tr>
   {% endfor %} 

 </table>
 {% endif %}
 

 <hr>



{% endblock %}

app01/templates/app01/gravarFolhaLayout.html
{% extends 'base2.html' %}


{% block content %}
<br/>

<div class="container">
<p align="center">{{ titulo }}</p>

    
   <form action="{% url 'app01:imprimirFolhaLayout' %}" method="post">
    {%csrf_token%}

   {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

   
<div class="row">   

<div class="form-group">
      
    
    <div class="col">
    <label for="id_municipio" class="col-form-label">Município</label>
    <select name="municipio"  id="id_municipio" class="form-control" required>
      <option value=""></option>
      {% for municipio in municipios %}
        <option value="{{ municipio.id_municipio }}">{{ municipio.municipio }}</option>
      {% endfor %}
    </select>   
    </div>


    <div class="col">
    <label for="id_ano" class="col-form-label">Ano</label>
    <select name="ano"  id="id_ano" class="form-control" required>
      <option value=""></option>
      <option value="2021">2021</option>
      <option value="2022">2022</option>
      <option value="2023">2023</option>
    </select>   

    <label for="id_mes" class="col-form-label">Mes</label>
    <select name="mes"  id="id_mes" class="form-control" required>
      <option value=""></option>
      <option value="01">Janeiro</option>
      <option value="02">Fevereiro</option>
      <option value="03">Marco</option>
      <option value="04">Abril</option>
      <option value="05">Maio</option>
      <option value="06">JUnho</option>
      <option value="07">Julho</option>
      <option value="08">Agosto</option>
      <option value="09">Setembro</option>
      <option value="10">Outubro</option>
      <option value="11">Novembro</option>
      <option value="12">Dezembro</option>

    </select>   

    </div>

    <br>

    <h2><span class="mensagem">{{ mensagem }}</span></h2>

</div>    
</div>  
  
  <br><br>


    <p><span style="display:none">
    <input type="submit" id="submit" value="Entrar 2" >
    </span></p>


    <p>
    <button class="btn btn-success" id="bt_submit" onclick="fnSubmit();" >Executar</button>
    </p>
    <div id="msgDiv" style="display:none">Processo iniciado...</div>



<script>

function fnSubmit(){
  var dados_ok=0;
      if (document.getElementById("id_municipio").value!=""){
        if (document.getElementById("id_ano").value!=""){
          if (document.getElementById("id_mes").value!=""){
             dados_ok=1;
          }
        }
      }
   if (dados_ok==1){
    document.getElementById("bt_submit").disabled=true;
    document.getElementById("msgDiv").style.display = "block";
    document.getElementById("submit").click();
   }

}


</script>
<style>
#msgDiv {
  width: 550px;
  height: 150px;
  background-color: lightblue;
  font-size: 24px;
}

.mensagem {
  color: red;

}

</style>

   </form>
   <hr>
</div>
</div>
</div>
{% endblock %}